name: Sync Fork

on:
  push:
    branches:
      - main  # 메인 브랜치에 변경 사항이 있을 때 실행

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send repository_dispatch event to fork
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.FORK_SYNC_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/Auctify-client/dispatches \
          -d '{"event_type": "sync_fork"}'
