name: Sync Fork

on:
  repository_dispatch:
    types: [sync_fork]  # repository_dispatch 이벤트가 실행되면 시작

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/next-work-team/Auctify-client.git

      - name: Fetch and merge upstream changes
        run: |
          git fetch upstream main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes to forked repository
        run: git push origin main